-- Crea e usa lo schema
CREATE DATABASE IF NOT EXISTS project_work
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;
USE project_work;

-- =========================
-- TABELLE
-- =========================

CREATE TABLE `PW_PROV_Province` (
  `PROV_ID` INT NOT NULL AUTO_INCREMENT,
  `PROV_Descrizione` VARCHAR(100) NULL,
  PRIMARY KEY (`PROV_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `PW_COMU_COMUNI` (
  `COMU_ID` INT NOT NULL AUTO_INCREMENT,
  `COMU_DESCRIZIONE` VARCHAR(500) NULL,
  `COMU_CAP` VARCHAR(4) NULL,
  `COMU_PROV_ID` INT NULL,
  PRIMARY KEY (`COMU_ID`),
  KEY `ix_COMU_PROV_ID` (`COMU_PROV_ID`),
  CONSTRAINT `FK_COMU_COMUNI_PROV_Province`
    FOREIGN KEY (`COMU_PROV_ID`) REFERENCES `PW_PROV_Province`(`PROV_ID`)
    ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `PW_STAT_Stati_Prenotazione` (
  `STAT_ID` INT NOT NULL AUTO_INCREMENT,
  `STAT_Descrizione` VARCHAR(50) NULL,
  PRIMARY KEY (`STAT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `PW_TPAG_Tipo_Pagamenti` (
  `TPAG_ID` INT NOT NULL AUTO_INCREMENT,
  `TPAG_Descrizione` VARCHAR(100) NULL,
  PRIMARY KEY (`TPAG_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `PW_TBIG_Tipologia_Biglietti` (
  `TBIG_ID` INT NOT NULL AUTO_INCREMENT,
  `TBIG_Descrizione` VARCHAR(100) NULL,
  `TBIG_ANNI` INT NULL,
  `TBIG_Perc_sconto` DECIMAL(18,2) NULL,
  PRIMARY KEY (`TBIG_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `PW_TREN_Treni` (
  `TREN_ID` INT NOT NULL AUTO_INCREMENT,
  `TREN_modello` VARCHAR(50) NULL,
  `TREN_Numero` VARCHAR(10) NULL,
  PRIMARY KEY (`TREN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `PW_CLAS_Classi` (
  `CLAS_ID` INT NOT NULL AUTO_INCREMENT,
  `CLAS_Descrizione` VARCHAR(50) NULL,
  PRIMARY KEY (`CLAS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `PW_STAZ_Stazioni` (
  `STAZ_Id` INT NOT NULL AUTO_INCREMENT,
  `STAZ_Nome` VARCHAR(100) NULL,
  `STAZ_Descrizione` VARCHAR(1000) NULL,
  `STAZ_COMUNI_ID` INT NULL,
  PRIMARY KEY (`STAZ_Id`),
  KEY `ix_STAZ_COMUNI_ID` (`STAZ_COMUNI_ID`),
  CONSTRAINT `FK_STAZ_Stazioni_COMU_COMUNI`
    FOREIGN KEY (`STAZ_COMUNI_ID`) REFERENCES `PW_COMU_COMUNI`(`COMU_ID`)
    ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `PW_TRAT_Tratte` (
  `TRAT_ID` INT NOT NULL AUTO_INCREMENT,
  `TRAT_STAZ_ID_Partenza` INT NULL,
  `TRAT_STAZ_ID_Arrivo` INT NULL,
  `TRAT_Distanza_Km` DECIMAL(18,2) NULL,
  `TRAT_DURATA_PREVISTA` DECIMAL(18,2) NULL,
  `TRAT_COSTO` DECIMAL(19,4) NULL,
  PRIMARY KEY (`TRAT_ID`),
  KEY `ix_TRAT_STAZ_ID_Partenza` (`TRAT_STAZ_ID_Partenza`),
  KEY `ix_TRAT_STAZ_ID_Arrivo` (`TRAT_STAZ_ID_Arrivo`),
  CONSTRAINT `FK_TRAT_Tratte_STAZ_Stazioni_p`
    FOREIGN KEY (`TRAT_STAZ_ID_Partenza`) REFERENCES `PW_STAZ_Stazioni`(`STAZ_Id`)
    ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT `FK_TRAT_Tratte_STAZ_Stazioni_a`
    FOREIGN KEY (`TRAT_STAZ_ID_Arrivo`) REFERENCES `PW_STAZ_Stazioni`(`STAZ_Id`)
    ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `PW_PASS_Passeggeri` (
  `PASS_id` INT NOT NULL AUTO_INCREMENT,
  `PASS_nome` VARCHAR(50) NULL,
  `PASS_cognome` VARCHAR(50) NULL,
  `PASS_ragione_sociale` VARCHAR(50) NULL,
  `PASS_partita_iva` VARCHAR(11) NULL,
  `PASS_codice_fiscale` VARCHAR(16) NULL,
  `PASS_Data_Nascita` DATETIME NULL,
  `PASS_telefono` VARCHAR(50) NULL,
  `PASS_email` VARCHAR(100) NULL,
  `PASS_password_cifrata` VARCHAR(255) NULL,
  `PASS_COMU_ID_fiscale` INT NULL,
  `PASS_Indirizzo_Fiscale` VARCHAR(255) NULL,
  `PASS_Cap_fiscale` VARCHAR(255) NULL,
  `PASS_COMU_ID_recapito` INT NULL,
  `PASS_Indirizzo_recapito` VARCHAR(255) NULL,
  `PASS_Cap_recapito` VARCHAR(255) NULL,
  `PASS_Numero_Tessera` VARCHAR(50) NULL,
  PRIMARY KEY (`PASS_id`),
  KEY `ix_PASS_COMU_ID_fiscale` (`PASS_COMU_ID_fiscale`),
  KEY `ix_PASS_COMU_ID_recapito` (`PASS_COMU_ID_recapito`),
  CONSTRAINT `FK_PASS_Passeggeri_COMU_COMUNI_fiscale`
    FOREIGN KEY (`PASS_COMU_ID_fiscale`) REFERENCES `PW_COMU_COMUNI`(`COMU_ID`)
    ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT `FK_PASS_Passeggeri_COMU_COMUNI_recapito`
    FOREIGN KEY (`PASS_COMU_ID_recapito`) REFERENCES `PW_COMU_COMUNI`(`COMU_ID`)
    ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `PW_PREN_Prenotazioni` (
  `PREN_ID` INT NOT NULL AUTO_INCREMENT,
  `PREN_PASS_ID` INT NULL,
  `PREN_Data_Prenotazione` DATETIME NULL,
  `PREN_STAT_ID` INT NULL,
  PRIMARY KEY (`PREN_ID`),
  KEY `ix_PREN_PASS_ID` (`PREN_PASS_ID`),
  KEY `ix_PREM_STAT_ID` (`PREN_STAT_ID`),
  CONSTRAINT `FK_PREN_Prenotazioni_PASS_Passeggeri`
    FOREIGN KEY (`PREN_PASS_ID`) REFERENCES `PW_PASS_Passeggeri`(`PASS_id`)
    ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT `FK_PREN_Prenotazioni_STAT_Stati_Prenotazione`
    FOREIGN KEY (`PREN_STAT_ID`) REFERENCES `PW_STAT_Stati_Prenotazione`(`STAT_ID`)
    ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `PW_PAGA_Pagamenti` (
  `PAGA_ID` INT NOT NULL AUTO_INCREMENT,
  `PAGA_PREN_ID` INT NULL,
  `PAGA_TPAG_ID` INT NULL,
  `PAGA_Data_pagamento` DATE NULL,
  `PAGA_Data_Valuta` DATE NULL,
  `PAGA_Data_Contabilizzazione` DATE NULL,
  `PAGA_FL_Esito` TINYINT(1) NULL,
  PRIMARY KEY (`PAGA_ID`),
  KEY `ix_PAGA_PREN_ID` (`PAGA_PREN_ID`),
  KEY `ix_PAGA_TPAG_ID` (`PAGA_TPAG_ID`),
  CONSTRAINT `FK_PAGA_Pagamenti_TPAG_Tipo_Pagamenti`
    FOREIGN KEY (`PAGA_TPAG_ID`) REFERENCES `PW_TPAG_Tipo_Pagamenti`(`TPAG_ID`)
    ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT `FK_PAGA_Pagamenti_PREN_Prenotazioni`
    FOREIGN KEY (`PAGA_PREN_ID`) REFERENCES `PW_PREN_Prenotazioni`(`PREN_ID`)
    ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `PW_CARR_Carrozze` (
  `CARR_ID` INT NOT NULL AUTO_INCREMENT,
  `CARR_TREN_ID` INT NULL,
  `CARR_Num_Posti` INT NULL,
  `CARR_CLAS_ID` INT NULL,
  `CARR_Numero` INT NOT NULL,
  PRIMARY KEY (`CARR_ID`),
  KEY `ix_CARR_TREN_ID` (`CARR_TREN_ID`),
  KEY `ix_CARR_CLAS_ID` (`CARR_CLAS_ID`),
  CONSTRAINT `FK_CARR_Carrozze_TREN_Treni`
    FOREIGN KEY (`CARR_TREN_ID`) REFERENCES `PW_TREN_Treni`(`TREN_ID`)
    ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT `FK_CARR_Carrozze_CLAS_Classi`
    FOREIGN KEY (`CARR_CLAS_ID`) REFERENCES `PW_CLAS_Classi`(`CLAS_ID`)
    ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE `PW_ORAR_Orari` (
  `ORAR_ID` INT NOT NULL AUTO_INCREMENT,
  `ORAR_TREN_ID` INT NULL,
  `ORAR_TRAT_ID` INT NULL,
  `ORAR_DATA_Partenza` DATE NULL,
  `ORAR_Data_Arrivo` DATE NULL,
  `ORAR_Ora_Partenza` TIME NULL,
  `ORAR_Ora_Arrivo` TIME NULL,
  PRIMARY KEY (`ORAR_ID`),
  KEY `ix_ORAR_TREN_ID` (`ORAR_TREN_ID`),
  KEY `ix_ORAR_TRAT_ID` (`ORAR_TRAT_ID`),
  CONSTRAINT `FK_ORAR_Orari_TREN_Treni`
    FOREIGN KEY (`ORAR_TREN_ID`) REFERENCES `PW_TREN_Treni`(`TREN_ID`)
    ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT `FK_ORAR_Orari_TRAT_Tratte`
    FOREIGN KEY (`ORAR_TRAT_ID`) REFERENCES `PW_TRAT_Tratte`(`TRAT_ID`)
    ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `PW_BIGL_Biglietti` (
  `BIGL_ID` INT NOT NULL AUTO_INCREMENT,
  `BIGL_PREN_ID` INT NULL,
  `BIGL_TBIG_ID` INT NULL,
  `BIGL_Prezzo` DECIMAL(19,4) NULL,
  `BIGL_QR_Code` VARCHAR(1000) NULL,
  PRIMARY KEY (`BIGL_ID`),
  KEY `ix_BIGL_PREN_ID` (`BIGL_PREN_ID`),
  KEY `ix_BIGL_TBIG_ID` (`BIGL_TBIG_ID`),
  CONSTRAINT `FK_BIGL_Biglietti_PREN_Prenotazioni`
    FOREIGN KEY (`BIGL_PREN_ID`) REFERENCES `PW_PREN_Prenotazioni`(`PREN_ID`)
    ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT `FK_BIGL_Biglietti_TBIG_Tipologia_Biglietti`
    FOREIGN KEY (`BIGL_TBIG_ID`) REFERENCES `PW_TBIG_Tipologia_Biglietti`(`TBIG_ID`)
    ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `PW_BIOR_Bieglietti_Orari` (
  `BIOR_ID` INT NOT NULL AUTO_INCREMENT,
  `BIOR_BIGL_ID` INT NULL,
  `BIOR_ORAR_ID` INT NULL,
  PRIMARY KEY (`BIOR_ID`),
  KEY `ix_BIOR_BIGL_ID` (`BIOR_BIGL_ID`),
  KEY `ix_BIOR_ORAR_ID` (`BIOR_ORAR_ID`),
  CONSTRAINT `FK_BIOR_Bieglietti_Orari_BIGL_Biglietti`
    FOREIGN KEY (`BIOR_BIGL_ID`) REFERENCES `PW_BIGL_Biglietti`(`BIGL_ID`)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT `FK_BIOR_Bieglietti_Orari_ORAR_Orari`
    FOREIGN KEY (`BIOR_ORAR_ID`) REFERENCES `PW_ORAR_Orari`(`ORAR_ID`)
    ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
